// This file is @generated by prost-build.
#![allow(clippy::trivially_copy_pass_by_ref)]

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Empty {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpsertThreadSpawnEdgeRequest {
    #[prost(string, tag = "1")]
    pub parent_thread_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub child_thread_id: ::prost::alloc::string::String,
    /// Servers must reject THREAD_SPAWN_EDGE_STATUS_UNSPECIFIED.
    #[prost(enumeration = "ThreadSpawnEdgeStatus", tag = "3")]
    pub status: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetThreadSpawnEdgeStatusRequest {
    #[prost(string, tag = "1")]
    pub child_thread_id: ::prost::alloc::string::String,
    /// Servers must reject THREAD_SPAWN_EDGE_STATUS_UNSPECIFIED.
    #[prost(enumeration = "ThreadSpawnEdgeStatus", tag = "2")]
    pub status: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListThreadSpawnChildrenRequest {
    #[prost(string, tag = "1")]
    pub parent_thread_id: ::prost::alloc::string::String,
    /// Absent means all statuses.
    #[prost(enumeration = "ThreadSpawnEdgeStatus", optional, tag = "2")]
    pub status_filter: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListThreadSpawnChildrenResponse {
    /// Ordered child thread ids.
    #[prost(string, repeated, tag = "1")]
    pub thread_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListThreadSpawnDescendantsRequest {
    #[prost(string, tag = "1")]
    pub root_thread_id: ::prost::alloc::string::String,
    /// Absent means all statuses.
    #[prost(enumeration = "ThreadSpawnEdgeStatus", optional, tag = "2")]
    pub status_filter: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListThreadSpawnDescendantsResponse {
    /// Ordered descendant thread ids.
    #[prost(string, repeated, tag = "1")]
    pub thread_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ThreadSpawnEdgeStatus {
    Unspecified = 0,
    Open = 1,
    Closed = 2,
}
impl ThreadSpawnEdgeStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "THREAD_SPAWN_EDGE_STATUS_UNSPECIFIED",
            Self::Open => "THREAD_SPAWN_EDGE_STATUS_OPEN",
            Self::Closed => "THREAD_SPAWN_EDGE_STATUS_CLOSED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "THREAD_SPAWN_EDGE_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "THREAD_SPAWN_EDGE_STATUS_OPEN" => Some(Self::Open),
            "THREAD_SPAWN_EDGE_STATUS_CLOSED" => Some(Self::Closed),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod agent_graph_store_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::http::Uri;
    use tonic::codegen::*;
    #[derive(Debug, Clone)]
    pub struct AgentGraphStoreClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl AgentGraphStoreClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> AgentGraphStoreClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> AgentGraphStoreClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                    http::Request<tonic::body::Body>,
                    Response = http::Response<
                        <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                    >,
                >,
            <T as tonic::codegen::Service<http::Request<tonic::body::Body>>>::Error:
                Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            AgentGraphStoreClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn upsert_thread_spawn_edge(
            &mut self,
            request: impl tonic::IntoRequest<super::UpsertThreadSpawnEdgeRequest>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/codex.agent_graph_store.v1.AgentGraphStore/UpsertThreadSpawnEdge",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "codex.agent_graph_store.v1.AgentGraphStore",
                "UpsertThreadSpawnEdge",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn set_thread_spawn_edge_status(
            &mut self,
            request: impl tonic::IntoRequest<super::SetThreadSpawnEdgeStatusRequest>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/codex.agent_graph_store.v1.AgentGraphStore/SetThreadSpawnEdgeStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "codex.agent_graph_store.v1.AgentGraphStore",
                "SetThreadSpawnEdgeStatus",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_thread_spawn_children(
            &mut self,
            request: impl tonic::IntoRequest<super::ListThreadSpawnChildrenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListThreadSpawnChildrenResponse>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/codex.agent_graph_store.v1.AgentGraphStore/ListThreadSpawnChildren",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "codex.agent_graph_store.v1.AgentGraphStore",
                "ListThreadSpawnChildren",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_thread_spawn_descendants(
            &mut self,
            request: impl tonic::IntoRequest<super::ListThreadSpawnDescendantsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListThreadSpawnDescendantsResponse>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/codex.agent_graph_store.v1.AgentGraphStore/ListThreadSpawnDescendants",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "codex.agent_graph_store.v1.AgentGraphStore",
                "ListThreadSpawnDescendants",
            ));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod agent_graph_store_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with AgentGraphStoreServer.
    #[async_trait]
    pub trait AgentGraphStore: std::marker::Send + std::marker::Sync + 'static {
        async fn upsert_thread_spawn_edge(
            &self,
            request: tonic::Request<super::UpsertThreadSpawnEdgeRequest>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status>;
        async fn set_thread_spawn_edge_status(
            &self,
            request: tonic::Request<super::SetThreadSpawnEdgeStatusRequest>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status>;
        async fn list_thread_spawn_children(
            &self,
            request: tonic::Request<super::ListThreadSpawnChildrenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListThreadSpawnChildrenResponse>,
            tonic::Status,
        >;
        async fn list_thread_spawn_descendants(
            &self,
            request: tonic::Request<super::ListThreadSpawnDescendantsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListThreadSpawnDescendantsResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct AgentGraphStoreServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> AgentGraphStoreServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(inner: T, interceptor: F) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for AgentGraphStoreServer<T>
    where
        T: AgentGraphStore,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/codex.agent_graph_store.v1.AgentGraphStore/UpsertThreadSpawnEdge" => {
                    #[allow(non_camel_case_types)]
                    struct UpsertThreadSpawnEdgeSvc<T: AgentGraphStore>(pub Arc<T>);
                    impl<T: AgentGraphStore>
                        tonic::server::UnaryService<super::UpsertThreadSpawnEdgeRequest>
                        for UpsertThreadSpawnEdgeSvc<T>
                    {
                        type Response = super::Empty;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpsertThreadSpawnEdgeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AgentGraphStore>::upsert_thread_spawn_edge(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpsertThreadSpawnEdgeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/codex.agent_graph_store.v1.AgentGraphStore/SetThreadSpawnEdgeStatus" => {
                    #[allow(non_camel_case_types)]
                    struct SetThreadSpawnEdgeStatusSvc<T: AgentGraphStore>(pub Arc<T>);
                    impl<T: AgentGraphStore>
                        tonic::server::UnaryService<super::SetThreadSpawnEdgeStatusRequest>
                        for SetThreadSpawnEdgeStatusSvc<T>
                    {
                        type Response = super::Empty;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SetThreadSpawnEdgeStatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AgentGraphStore>::set_thread_spawn_edge_status(
                                    &inner, request,
                                )
                                .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SetThreadSpawnEdgeStatusSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/codex.agent_graph_store.v1.AgentGraphStore/ListThreadSpawnChildren" => {
                    #[allow(non_camel_case_types)]
                    struct ListThreadSpawnChildrenSvc<T: AgentGraphStore>(pub Arc<T>);
                    impl<T: AgentGraphStore>
                        tonic::server::UnaryService<super::ListThreadSpawnChildrenRequest>
                        for ListThreadSpawnChildrenSvc<T>
                    {
                        type Response = super::ListThreadSpawnChildrenResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListThreadSpawnChildrenRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AgentGraphStore>::list_thread_spawn_children(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListThreadSpawnChildrenSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/codex.agent_graph_store.v1.AgentGraphStore/ListThreadSpawnDescendants" => {
                    #[allow(non_camel_case_types)]
                    struct ListThreadSpawnDescendantsSvc<T: AgentGraphStore>(pub Arc<T>);
                    impl<T: AgentGraphStore>
                        tonic::server::UnaryService<super::ListThreadSpawnDescendantsRequest>
                        for ListThreadSpawnDescendantsSvc<T>
                    {
                        type Response = super::ListThreadSpawnDescendantsResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListThreadSpawnDescendantsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AgentGraphStore>::list_thread_spawn_descendants(
                                    &inner, request,
                                )
                                .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListThreadSpawnDescendantsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => Box::pin(async move {
                    let mut response = http::Response::new(tonic::body::Body::default());
                    let headers = response.headers_mut();
                    headers.insert(
                        tonic::Status::GRPC_STATUS,
                        (tonic::Code::Unimplemented as i32).into(),
                    );
                    headers.insert(
                        http::header::CONTENT_TYPE,
                        tonic::metadata::GRPC_CONTENT_TYPE,
                    );
                    Ok(response)
                }),
            }
        }
    }
    impl<T> Clone for AgentGraphStoreServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "codex.agent_graph_store.v1.AgentGraphStore";
    impl<T> tonic::server::NamedService for AgentGraphStoreServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
