// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HookAutoReviewDangerousHook } from "./HookAutoReviewDangerousHook";

export type HookAutoReviewCompletedNotification = { threadId: string, turnId: string, reviewedCount: number, trustedCount: number, dangerousCount: number, skippedCount: number, failedCount: number, dangerousHooks: Array<HookAutoReviewDangerousHook>, };
