// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpResourceReadParams = { threadId?: string | null,
/**
 * Optional environment used to read the resource. Threadless reads
 * currently support only `local`; thread-scoped requests must resolve to
 * the thread's selected primary environment until per-environment MCP
 * managers are available.
 */
environmentId?: string | null, server: string, uri: string, };
