// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillsListExtraRootsForCwd } from "./SkillsListExtraRootsForCwd";

export type SkillsListParams = {
/**
 * Optional environment to scan. Threadless `skills/list` currently
 * supports only `local` because config/plugin skill layers are still
 * loaded from local config files.
 */
environmentId?: string | null,
/**
 * When empty, defaults to the current session working directory.
 */
cwds?: Array<string>,
/**
 * When true, bypass the skills cache and re-scan skills from disk.
 */
forceReload?: boolean,
/**
 * Optional per-cwd extra roots to scan as user-scoped skills.
 */
perCwdExtraUserRoots?: Array<SkillsListExtraRootsForCwd> | null, };
