// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadLoadedSummary } from "./ThreadLoadedSummary";

export type ThreadLoadedListResponse = {
/**
 * Thread ids for sessions currently loaded in memory.
 */
data: Array<string>,
/**
 * Loaded-thread summaries for the returned page when `includeSummaries` is true.
 * Empty when summaries were not requested.
 */
summaries: Array<ThreadLoadedSummary>,
/**
 * Opaque cursor to pass to the next call to continue after the last item.
 * if None, there are no more items to return.
 */
nextCursor: string | null, };
