// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackUsageLimitBannerAction } from "./TrackUsageLimitBannerAction";
import type { UsageLimitBannerType } from "./UsageLimitBannerType";

export type TrackUsageLimitBannerParams = { action: TrackUsageLimitBannerAction, bannerType: UsageLimitBannerType, };
