// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageLimitBannerType = "workspace_member_credits_depleted" | "workspace_member_usage_limit_reached";
