/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageLimitNudge {
    #[serde(rename = "threshold")]
    pub threshold: u8,
    #[serde(rename = "action")]
    pub action: UsageLimitNudgeAction,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UsageLimitNudgeAction {
    #[serde(rename = "add_credits")]
    AddCredits,
    #[serde(rename = "upgrade")]
    Upgrade,
}
